2015-10-02 00:43:00 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
